Semantic embedding
Aleph-Alpha/aleph-alpha-client pull request #38
Opened 2022-07-25 14:02 UTC by ahartel

2022-07-25 14:31 UTC, benbrandt commented on README.md
> +
Add asymmetric example, doc + query

2022-07-27 11:23 UTC, volkerstampa requested changes
I propose a few minor changes.

2022-07-27 11:23 UTC, volkerstampa commented on README.md
> +def cosine_similarity(v1, v2):
I propose to add type hints.

2022-07-27 11:23 UTC, volkerstampa commented on aleph_alpha_client/__init__.py
> +    SemanticRepresentation,
I guess we should add the corresponding `..Response` classes as well (not only for the embedding case actually)

2022-07-27 11:23 UTC, volkerstampa commented on aleph_alpha_client/aleph_alpha_client.py
> +        model,
type hint

2022-07-27 11:23 UTC, volkerstampa commented on aleph_alpha_client/embedding.py
> +    """
? I do not think there is pydoc for members, is there? Usually this is just added to the doc of the class.

2022-07-27 11:23 UTC, volkerstampa commented on aleph_alpha_client/embedding.py
> +            model_version=json["model_version"], embedding=json["embedding"]
Alternatively `return SemanticEmbeddingResponse(**json)`

2022-07-28 11:23 UTC, merged